### ISSUE TITLE
Incompatibility with other scripts that use `bash-preexec`. 

### ISSUE THREAD

**Issue by qbouvet** [hopeseekr/bash-timer#3]
`bash-timer` is incompatible with other scripts that use `bash-preexec`, for instance [undistract-me](https://github.com/jml/undistract-me). 

This is because `bash-timer` defines variables `prexec` and `precmd`. Either these variables are already defined, and `bash-timer` overwrites them, or `bash-timer` defines them, and whichever `bash-prexec` script sourced afterwards overwrites them. 

The solution to this issue is to use the [array functions](https://github.com/rcaloras/bash-preexec#function-arrays) provided by `bash-preexec`. I made pull request #2 to that end (and I plan to open a similar pull-request for `undistract-me`).

Also, thanks for your script I really like it :)

**Comment by hopeseekr** [comment]
Merged! Thank you so much!!!
