### ISSUE TITLE
AUR Package

### ISSUE THREAD

**Issue by qbouvet** [hopeseekr/bash-timer#4]
Hi, 

I wanted to let you know that I created an Arch User Repository (AUR) entry for this repository. It consists of metadata (github URL, commit hash, ...) for `makepkg` [1], an arch linux tool that can create arch packages from source code. This means is that people can now call this command line tool to automatically download, package and install this script on their machines (which is convenient for me). 

Please let me know if for some reason this is a problem for you. 

Cheers !

[1] https://wiki.archlinux.org/index.php/Makepkg

**Comment by hopeseekr** [comment]
THIS IS AMAZING!!!!!!!!!!

Arch Linux is my day-to-day workhorse of choice!!!!!!!

Be sure to tell us here what the aur package is named!

The v1.0 branch will always contain the latest stable code. The [`install`](https://github.com/hopeseekr/bash-timer/blob/master/install) also has authoritative sha256 hashes.

**Comment by qbouvet** [comment]
Hey,

Sorry it took me a while to come back to this. 

The package is [over here](https://aur.archlinux.org/packages/bash-timer/). If you want to get involved in maintaining the package, I can list you as co-maintainer (or maintainer if you want, it's your code after all). In any case, the source points here so you are credited for the work.

Regarding the `v1.0` branch, I'm using the releases that you put on github, not branches and commits. This is easier (not need for git to install the package) and nicer in your package manager (it shows the release version and not the commit hash). I'll quickly update the package to retrieve directly the `.sh` and use the authoritative hash value for this file. 

EDIT: Okay, I just realised the content of the `bash-preexec` PR is not in the release. If you create a new release with the new stuff, I'll just update the pkgbuild. If I have no news I'll create a *-git pkgbuild based on the `v1.0`branch. Either works :)
